### ISSUE TITLE
blob ponyfill for file upload from cf workers?

### ISSUE THREAD

**Issue by phanirithvij** [ssttevee/js-cfw-formdata-polyfill#2]
Hi, thanks for this project. I was searching for a way to upload a file **from** a cf worker and found this,

I'm trying this using the blob ponyfill.

```js
import Blob from '@ssttevee/blob-ponyfill';

async function handleRequest(request) {
    const file = await fetch('https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/02_start_book_creator.png/640px-02_start_book_creator.png');
    let formData = new FormData();
    const arrbuffer = await file.arrayBuffer();
    const fileblob = new Blob([arrbuffer], {
      type: "image/png"
    });
    console.log(arrbuffer, formData, fileblob);
    formData.append("file", fileblob);
    var returned = fetch('https://file.io', {
      method: 'POST',
      body: formData
    });
}

handleRequest()
```

But in the network tab, the form data is being sent incorrectly, as `[object Object]` in the Request Payload.

[Screenshot](https://user-images.githubusercontent.com/29627898/104273787-6bdf0300-54c5-11eb-8aa1-59427165d387.png)

**Comment by ssttevee** [comment]
Unfortunately this library doesn't facilitate the formatting of `FormData` right now.

Although not currently supported, generating a `multipart/form-data` payload from the ponyfill class should be relatively easy by [following the RFC](https://tools.ietf.org/html/rfc7578). I think the hard part is figuring out how to unobtrusively make `fetch` recognize the class as a special body type instead of just calling `toString()`.

Returning the entire payload in `toString()` is also an option, but I suspect it will be memory intensive. Given that CloudFlare Workers, the target use case, has a low memory limit of 128MB, that's probably not a route I'd like to proceed.

With that said, the only other way I can think of right now is to shim `fetch` with special body handling logic. This is still not a particularly nice solution. Since the CloudFlare Workers environment doesn't implement the `ReadableStream` contructor, there will be a detached async loop pumping data into an identity `TransformStream`.

So, pick your poison, I guess.

**Comment by phanirithvij** [comment]
https://stackoverflow.com/a/65672740/8608146

**Comment by einkoro** [comment]
FYI CloudFlare support for File and Blob is available now. Sadly FormData still returns the strings instead of File objects so this polyfill is still needed but with a few minor changes it can be updated to work for formatting requests. I'll open a pull request shortly.
